---
- name: Add Elasticsearch repository.
  yum_repository:
    name: "elasticsearch-{{ es_major_version }}"
    description: "elasticsearch-{{ es_major_version }}"
    baseurl: "{{ es_yum_repo }}"
    gpgkey: "{{ es_yum_gpg }}"
    gpgcheck: "{{ es_yum_gpgcheck }}"
  when:
    - es_yum_repo is defined
    - es_yum_repo != ""

## Kibana Reporting
### source: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
- name: Install CentOS packages required for Kibana reporting
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - alsa-lib.x86_64
    - atk.x86_64
    - cups-libs.x86_64
    - gtk3.x86_64
    - ipa-gothic-fonts
    - libXcomposite.x86_64
    - libXcursor.x86_64
    - libXdamage.x86_64
    - libXext.x86_64
    - libXi.x86_64
    - libXrandr.x86_64
    - libXScrnSaver.x86_64
    - libXtst.x86_64
    - pango.x86_64
    - xorg-x11-fonts-100dpi
    - xorg-x11-fonts-75dpi
    - xorg-x11-fonts-cyrillic
    - xorg-x11-fonts-misc
    - xorg-x11-fonts-Type1
    - xorg-x11-utils
  register: _kibana_xpack_reporting_packages


- name: Update nss (related to kibana reporting feature)
  shell: yum update nss -y
  when: _kibana_xpack_reporting_packages
  become: true